version: "3.4"
services:
    web:
        build: .
        container_name: smartstore
        ports:
            - "88:5001"
        depends_on:
            - db
    db:
        image: mysql
        restart: always
        container_name: db
        environment:
            MYSQL_DATABASE: smartstore
            MYSQL_PASSWORD: "password"
            MYSQL_ROOT_PASSWORD: "password"
        ports:
          # <Port exposed> : < MySQL Port running inside container>
          - '3307:3306'
        expose:
          # Opens port 3306 on the container
          - '3306'
          # Where our data will be persisted
        volumes:
          - smartstore-db:/var/lib/mysql

volumes:
  smartstore-db:            